export const CurrencyList =[
    {"code":"AUD","name":"Australia Dollar","ispopular":true},
    {"code":"CAD","name":"Canada Dollar","ispopular":true},
    {"code":"CHF","name":"Switzerland Franc","ispopular":true},
    {"code":"CNY","name":"China Yuan Renminbi","ispopular":true},
    {"code":"EUR","name":"Euro Member Countries","ispopular":true},
    {"code":"GBP","name":"United Kingdom Pound","ispopular":true},
    {"code":"INR","name":"India Rupee","ispopular":true},
    {"code":"JPY","name":"Japan Yen","ispopular":true},
    {"code":"MYR","name":"Malaysia Ringgit","ispopular":true},
    {"code":"SGD","name":"Singapore Dollar","ispopular":true},
    {"code":"USD","name":"United States Dollar","ispopular":true},
    {"code":"BGN","name":"Bulgaria Lev","ispopular":false},
    {"code":"BRL","name":"Brazil Real","ispopular":false},
    {"code":"CZK","name":"Czech Republic Koruna","ispopular":false},
    {"code":"DKK","name":"Denmark Krone","ispopular":false},
    {"code":"HKD","name":"Hong Kong Dollar","ispopular":false},
    {"code":"HRK","name":"Croatia Kuna","ispopular":false},
    {"code":"HUF","name":"Hungary Forint","ispopular":false},
    {"code":"IDR","name":"Indonesia Rupiah","ispopular":false},
    {"code":"ILS","name":"Israel Shekel","ispopular":false},
    {"code":"ISK","name":"Iceland Krona","ispopular":false},
    {"code":"KRW","name":"Korea (South) Won","ispopular":false},
    {"code":"MXN","name":"Mexico Peso","ispopular":false},
    {"code":"NOK","name":"Norway Krone","ispopular":false},
    {"code":"NZD","name":"New Zealand Dollar","ispopular":false},
    {"code":"PHP","name":"Philippines Peso","ispopular":false},
    {"code":"PLN","name":"Poland Zloty","ispopular":false},
    {"code":"RON","name":"Romania Leu","ispopular":false},
    {"code":"RUB","name":"Russia Ruble","ispopular":false},
    {"code":"SEK","name":"Sweden Krona","ispopular":false},
    {"code":"THB","name":"Thailand Baht","ispopular":false},
    {"code":"TRY","name":"Turkey Lira","ispopular":false},
    {"code":"ZAR","name":"South Africa Rand","ispopular":false}
];